### ISSUE TITLE
我的目录结构跟你的不一样，用的时候提示错误

### ISSUE THREAD

**Issue by coolskull** [weilao/gulp-include-tag#1]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, no such file or directory 'g:\newSouthGate\common\head.html'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at getFileContent (g:\newSouthGate\node_modules\gulp-include-tag\node_modules\include-tag\dist\includeTag.js:4:15)
    at g:\newSouthGate\node_modules\gulp-include-tag\node_modules\include-tag\dist\includeTag.js:19:18
    at String.replace (native)
    at includeTag (g:\newSouthGate\node_modules\gulp-include-tag\node_modules\include-tag\dist\includeTag.js:10:21)
    at DestroyableTransform._transform (g:\newSouthGate\node_modules\gulp-include-tag\index.js:19:40)
    at DestroyableTransform.Transform._read (g:\newSouthGate\node_modules\gulp-include-tag\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (g:\newSouthGate\node_modules\gulp-include-tag\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:172:12)

Process finished with exit code 1

**Comment by coolskull** [comment]
谢谢大神

**Comment by ValorLin** [comment]
Thanks for the feedback.
